In [2]:
ruta_txt = 'C:/Users/artur/Desktop/TFG/textos/textoplano.txt'
with open(ruta_txt, 'r', encoding='utf-8') as f:
    raw = f.read()
print(raw[:500])

A black hole is a massive, compact astronomical object so dense that its gravity prevents anything from escaping, even light. Albert Einstein's theory of general relativity predicts that a sufficiently compact mass will form a black hole.The boundary of no escape is called the event horizon. A black hole has a great effect on the fate and circumstances of an object crossing it, but has no locally detectable features according to general relativity. In many ways, a black hole acts like an ideal b


In [3]:
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp(raw)
sentences = list(doc.sents)
for sent in sentences[:5]:
    print(sent)

A black hole is a massive, compact astronomical object so dense that its gravity prevents anything from escaping, even light.
Albert Einstein's theory of general relativity predicts that a sufficiently compact mass will form a black hole.
The boundary of no escape is called the event horizon.
A black hole has a great effect on the fate and circumstances of an object crossing it, but has no locally detectable features according to general relativity.
In many ways, a black hole acts like an ideal black body, as it reflects no light.


In [4]:
import nltk
from nltk.tokenize import word_tokenize
tokens = word_tokenize(raw)
print(tokens[:10])
print('\n')

for token in doc[:10]:
    print(token.text, '=>', token.pos_, '=>', token.tag_)

['A', 'black', 'hole', 'is', 'a', 'massive', ',', 'compact', 'astronomical', 'object']


A => DET => DT
black => ADJ => JJ
hole => NOUN => NN
is => AUX => VBZ
a => DET => DT
massive => ADJ => JJ
, => PUNCT => ,
compact => ADJ => JJ
astronomical => ADJ => JJ
object => NOUN => NN


In [5]:
import nltk
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
filtered_tokens = [token for token in tokens if token.lower() not in stop_words and token.isalpha()]
print(filtered_tokens[:10])
print('\n')

doc_filtrado = nlp(" ".join(filtered_tokens))

for token in doc_filtrado[:10]:
    print(token.text, '=>', token.pos_, '=>', token.tag_)

['black', 'hole', 'massive', 'compact', 'astronomical', 'object', 'dense', 'gravity', 'prevents', 'anything']


black => ADJ => JJ
hole => NOUN => NN
massive => ADJ => JJ
compact => ADJ => JJ
astronomical => ADJ => JJ
object => NOUN => NN
dense => ADJ => JJ
gravity => NOUN => NN
prevents => VERB => VBZ
anything => PRON => NN


In [6]:
from nltk.stem import SnowballStemmer
stemmer = SnowballStemmer('english')
stems = [stemmer.stem(token) for token in filtered_tokens]

print(stems[:20])

['black', 'hole', 'massiv', 'compact', 'astronom', 'object', 'dens', 'graviti', 'prevent', 'anyth', 'escap', 'even', 'light', 'albert', 'einstein', 'theori', 'general', 'relat', 'predict', 'suffici']


In [7]:
lemmas = [token.lemma_ for token in doc_filtrado if token.is_alpha]
print(lemmas[:20])

['black', 'hole', 'massive', 'compact', 'astronomical', 'object', 'dense', 'gravity', 'prevent', 'anything', 'escape', 'even', 'light', 'Albert', 'Einstein', 'theory', 'general', 'relativity', 'predict', 'sufficiently']


In [18]:
from tensorflow.keras.preprocessing.text import Tokenizer
limited_lemmas = lemmas[:20]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(limited_lemmas)
tokenizer.word_index

{'black': 1,
 'hole': 2,
 'massive': 3,
 'compact': 4,
 'astronomical': 5,
 'object': 6,
 'dense': 7,
 'gravity': 8,
 'prevent': 9,
 'anything': 10,
 'escape': 11,
 'even': 12,
 'light': 13,
 'albert': 14,
 'einstein': 15,
 'theory': 16,
 'general': 17,
 'relativity': 18,
 'predict': 19,
 'sufficiently': 20}

In [19]:
encoded = tokenizer.texts_to_sequences(limited_lemmas)
encoded = [item[0] for item in encoded if len(item) > 0]
print(encoded)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [20]:
import numpy as np
from keras.utils import to_categorical
vocab_size = len(tokenizer.word_index) + 1    
x = np.array(encoded[:-1]).reshape(-1, 1)  # input: cada palabra como secuencia de un paso
y = to_categorical(encoded[1:], num_classes=len(tokenizer.word_index) + 1)
print(x, y)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]] [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0

In [21]:
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense

modelo = Sequential()                                           
modelo.add(Embedding(vocab_size, 10)) 
modelo.add(LSTM(50))                                        
modelo.add(Dense(vocab_size, activation='softmax'))           

modelo.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])       

In [22]:
modelo.fit(x, y, epochs=120, verbose=2)

Epoch 1/120
1/1 - 2s - 2s/step - accuracy: 0.0000e+00 - loss: 3.0459
Epoch 2/120
1/1 - 0s - 56ms/step - accuracy: 0.0000e+00 - loss: 3.0452
Epoch 3/120
1/1 - 0s - 61ms/step - accuracy: 0.0000e+00 - loss: 3.0445
Epoch 4/120
1/1 - 0s - 51ms/step - accuracy: 0.0526 - loss: 3.0438
Epoch 5/120
1/1 - 0s - 48ms/step - accuracy: 0.0526 - loss: 3.0431
Epoch 6/120
1/1 - 0s - 40ms/step - accuracy: 0.0526 - loss: 3.0424
Epoch 7/120
1/1 - 0s - 40ms/step - accuracy: 0.0526 - loss: 3.0417
Epoch 8/120
1/1 - 0s - 51ms/step - accuracy: 0.0526 - loss: 3.0410
Epoch 9/120
1/1 - 0s - 45ms/step - accuracy: 0.0526 - loss: 3.0403
Epoch 10/120
1/1 - 0s - 47ms/step - accuracy: 0.0526 - loss: 3.0396
Epoch 11/120
1/1 - 0s - 40ms/step - accuracy: 0.1053 - loss: 3.0388
Epoch 12/120
1/1 - 0s - 43ms/step - accuracy: 0.1053 - loss: 3.0381
Epoch 13/120
1/1 - 0s - 44ms/step - accuracy: 0.1579 - loss: 3.0374
Epoch 14/120
1/1 - 0s - 47ms/step - accuracy: 0.2105 - loss: 3.0366
Epoch 15/120
1/1 - 0s - 47ms/step - accuracy: 0

In [23]:
modelo.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ (None, 1, 10)               │             210 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ (None, 50)                  │          12,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 21)                  │           1,071 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 40,445 (157.99 KB)

 Trainable params: 13,481 (52.66 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 26,964 (105.33 KB)

In [24]:
in_text = 'black'
print("Input:", in_text)
encoded = tokenizer.texts_to_sequences([in_text])[0]
encoded = np.array(encoded).reshape(1,1)
yhat = modelo.predict(encoded, verbose=0)
yhat_index = np.argmax(yhat)
for word, index in tokenizer.word_index.items():
	if index == yhat_index:
		print("Output:", word)

Input: black
Output: hole


In [25]:
def generate_seq(modelo, tokenizer, seed_text, n_words):
    in_text = seed_text
    result = seed_text
    
    for _ in range(n_words):
        # codificamos palabra a entero
        encoded = tokenizer.texts_to_sequences([in_text])[0]
        encoded = np.array(encoded).reshape(1, 1)  # (batch=1, timestep=1)

        # predecimos la siguiente palabra
        yhat = modelo.predict(encoded, verbose=0)
        yhat_index = np.argmax(yhat)

        # convertimos índice a palabra
        out_word = ''
        for word, index in tokenizer.word_index.items():
            if index == yhat_index:
                out_word = word
                break

        # añadimos palabra generada al texto
        in_text = out_word
        result += ' ' + out_word

    return result

In [26]:
generate_seq(modelo, tokenizer, seed_text='black', n_words=10)

'black hole massive compact astronomical object dense gravity prevent general compact'