In [2]:
ruta_txt = 'C:/Users/artur/Desktop/TFG/textos/textoplano.txt'
with open(ruta_txt, 'r', encoding='utf-8') as f:
    raw = f.read()
print(raw[:500])

A black hole is a massive, compact astronomical object so dense that its gravity prevents anything from escaping, even light. Albert Einstein's theory of general relativity predicts that a sufficiently compact mass will form a black hole.The boundary of no escape is called the event horizon. A black hole has a great effect on the fate and circumstances of an object crossing it, but has no locally detectable features according to general relativity. In many ways, a black hole acts like an ideal b


In [3]:
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp(raw)
sentences = list(doc.sents)
for sent in sentences[:5]:
    print(sent)

A black hole is a massive, compact astronomical object so dense that its gravity prevents anything from escaping, even light.
Albert Einstein's theory of general relativity predicts that a sufficiently compact mass will form a black hole.
The boundary of no escape is called the event horizon.
A black hole has a great effect on the fate and circumstances of an object crossing it, but has no locally detectable features according to general relativity.
In many ways, a black hole acts like an ideal black body, as it reflects no light.


In [4]:
import nltk
from nltk.tokenize import word_tokenize
tokens = word_tokenize(raw)
print(tokens[:10])
print('\n')

for token in doc[:10]:
    print(token.text, '=>', token.pos_, '=>', token.tag_)

['A', 'black', 'hole', 'is', 'a', 'massive', ',', 'compact', 'astronomical', 'object']


A => DET => DT
black => ADJ => JJ
hole => NOUN => NN
is => AUX => VBZ
a => DET => DT
massive => ADJ => JJ
, => PUNCT => ,
compact => ADJ => JJ
astronomical => ADJ => JJ
object => NOUN => NN


In [5]:
import nltk
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
filtered_tokens = [token for token in tokens if token.lower() not in stop_words and token.isalpha()]
print(filtered_tokens[:10])
print('\n')

doc_filtrado = nlp(" ".join(filtered_tokens))

for token in doc_filtrado[:10]:
    print(token.text, '=>', token.pos_, '=>', token.tag_)

['black', 'hole', 'massive', 'compact', 'astronomical', 'object', 'dense', 'gravity', 'prevents', 'anything']


black => ADJ => JJ
hole => NOUN => NN
massive => ADJ => JJ
compact => ADJ => JJ
astronomical => ADJ => JJ
object => NOUN => NN
dense => ADJ => JJ
gravity => NOUN => NN
prevents => VERB => VBZ
anything => PRON => NN


In [6]:
from nltk.stem import SnowballStemmer
stemmer = SnowballStemmer('english')
stems = [stemmer.stem(token) for token in filtered_tokens]

print(stems[:20])

['black', 'hole', 'massiv', 'compact', 'astronom', 'object', 'dens', 'graviti', 'prevent', 'anyth', 'escap', 'even', 'light', 'albert', 'einstein', 'theori', 'general', 'relat', 'predict', 'suffici']


In [7]:
lemmas = [token.lemma_ for token in doc_filtrado if token.is_alpha]
print(lemmas[:20])

['black', 'hole', 'massive', 'compact', 'astronomical', 'object', 'dense', 'gravity', 'prevent', 'anything', 'escape', 'even', 'light', 'Albert', 'Einstein', 'theory', 'general', 'relativity', 'predict', 'sufficiently']


In [8]:
from tensorflow.keras.preprocessing.text import Tokenizer
limited_lemmas = lemmas[:20]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(limited_lemmas)
tokenizer.word_index

{'black': 1,
 'hole': 2,
 'massive': 3,
 'compact': 4,
 'astronomical': 5,
 'object': 6,
 'dense': 7,
 'gravity': 8,
 'prevent': 9,
 'anything': 10,
 'escape': 11,
 'even': 12,
 'light': 13,
 'albert': 14,
 'einstein': 15,
 'theory': 16,
 'general': 17,
 'relativity': 18,
 'predict': 19,
 'sufficiently': 20}

In [9]:
encoded = tokenizer.texts_to_sequences(limited_lemmas)
encoded = [item[0] for item in encoded if len(item) > 0]
print(encoded)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [11]:
import numpy as np
from keras.utils import to_categorical
sequences = []
for i in range(2, len(encoded)):
    seq_x = encoded[i-2:i]  
    seq_y = encoded[i]      
    sequences.append((seq_x, seq_y))

# Preparar X, y
x = np.array([s[0] for s in sequences], dtype='int32') 
y = np.array([s[1] for s in sequences], dtype='int32')

vocab_size = len(tokenizer.word_index) + 1
y = to_categorical(y, num_classes=vocab_size)
print(x, "\n", y)

[[ 1  2]
 [ 2  3]
 [ 3  4]
 [ 4  5]
 [ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]
 [10 11]
 [11 12]
 [12 13]
 [13 14]
 [14 15]
 [15 16]
 [16 17]
 [17 18]
 [18 19]] 
 [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=10))
model.add(LSTM(50))
model.add(Dense(vocab_size, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)    

Epoch 1/200
1/1 - 2s - 2s/step - accuracy: 0.0000e+00 - loss: 3.0445
Epoch 2/200
1/1 - 0s - 46ms/step - accuracy: 0.0000e+00 - loss: 3.0434
Epoch 3/200
1/1 - 0s - 45ms/step - accuracy: 0.0000e+00 - loss: 3.0424
Epoch 4/200
1/1 - 0s - 45ms/step - accuracy: 0.1111 - loss: 3.0413
Epoch 5/200
1/1 - 0s - 43ms/step - accuracy: 0.1111 - loss: 3.0402
Epoch 6/200
1/1 - 0s - 39ms/step - accuracy: 0.1667 - loss: 3.0390
Epoch 7/200
1/1 - 0s - 42ms/step - accuracy: 0.1667 - loss: 3.0379
Epoch 8/200
1/1 - 0s - 38ms/step - accuracy: 0.1667 - loss: 3.0368
Epoch 9/200
1/1 - 0s - 45ms/step - accuracy: 0.1667 - loss: 3.0356
Epoch 10/200
1/1 - 0s - 42ms/step - accuracy: 0.1667 - loss: 3.0344
Epoch 11/200
1/1 - 0s - 34ms/step - accuracy: 0.1667 - loss: 3.0332
Epoch 12/200
1/1 - 0s - 48ms/step - accuracy: 0.1667 - loss: 3.0320
Epoch 13/200
1/1 - 0s - 43ms/step - accuracy: 0.1667 - loss: 3.0307
Epoch 14/200
1/1 - 0s - 37ms/step - accuracy: 0.1667 - loss: 3.0294
Epoch 15/200
1/1 - 0s - 43ms/step - accuracy: 0

In [16]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ (None, 2, 10)               │             210 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ (None, 50)                  │          12,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 21)                  │           1,071 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 40,445 (157.99 KB)

 Trainable params: 13,481 (52.66 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 26,964 (105.33 KB)

In [17]:
def generate_seq(model, tokenizer, seed_text, n_words):
    result = seed_text.split()
    in_text = seed_text
    for _ in range(n_words):
        encoded = tokenizer.texts_to_sequences([in_text.split()[-2:]])[0]
        encoded = np.array(encoded).reshape(1, 2)
        yhat = model.predict(encoded, verbose=0)
        yhat = np.argmax(yhat)
        out_word = ''
        for word, index in tokenizer.word_index.items():
            if index == yhat:
                out_word = word
                break
        in_text += ' ' + out_word
        result.append(out_word)
    return ' '.join(result)

In [22]:
print(generate_seq(model, tokenizer, seed_text='black hole', n_words=18))

black hole massive compact astronomical object dense gravity prevent anything escape even light albert einstein theory general relativity predict sufficiently
